services:
  postgres:
    image: postgres:16.2-alpine3.19
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  kiosk:
    container_name: kiosk
    build: .
    ports: 
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    env_file:
      - .env
