// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgstore

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Checkin struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	EventID   uuid.UUID        `db:"event_id" json:"event_id"`
	GuestID   uuid.UUID        `db:"guest_id" json:"guest_id"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Event struct {
	ID           uuid.UUID        `db:"id" json:"id"`
	Name         string           `db:"name" json:"name"`
	PrimaryColor string           `db:"primary_color" json:"primary_color"`
	Logo         string           `db:"logo" json:"logo"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
}

type Guest struct {
	ID             uuid.UUID        `db:"id" json:"id"`
	FullName       string           `db:"full_name" json:"full_name"`
	Email          pgtype.Text      `db:"email" json:"email"`
	DocumentNumber string           `db:"document_number" json:"document_number"`
	Occupation     pgtype.Text      `db:"occupation" json:"occupation"`
	ProfilePicture pgtype.Text      `db:"profile_picture" json:"profile_picture"`
	EventID        uuid.UUID        `db:"event_id" json:"event_id"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	DeletedAt      pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
}

type User struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	FullName  string           `db:"full_name" json:"full_name"`
	Email     string           `db:"email" json:"email"`
	Password  string           `db:"password" json:"password"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
}
