// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlitestore

import (
	"database/sql"
	"time"
)

type Checkin struct {
	ID        string    `db:"id" json:"id"`
	EventID   string    `db:"event_id" json:"event_id"`
	GuestID   string    `db:"guest_id" json:"guest_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type Event struct {
	ID           string       `db:"id" json:"id"`
	Name         string       `db:"name" json:"name"`
	PrimaryColor string       `db:"primary_color" json:"primary_color"`
	Logo         string       `db:"logo" json:"logo"`
	CreatedAt    time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time    `db:"updated_at" json:"updated_at"`
	DeletedAt    sql.NullTime `db:"deleted_at" json:"deleted_at"`
}

type Guest struct {
	ID             string         `db:"id" json:"id"`
	FullName       string         `db:"full_name" json:"full_name"`
	Email          sql.NullString `db:"email" json:"email"`
	DocumentNumber string         `db:"document_number" json:"document_number"`
	Occupation     sql.NullString `db:"occupation" json:"occupation"`
	ProfilePicture sql.NullString `db:"profile_picture" json:"profile_picture"`
	EventID        string         `db:"event_id" json:"event_id"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time      `db:"updated_at" json:"updated_at"`
	DeletedAt      sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type User struct {
	ID        string       `db:"id" json:"id"`
	FullName  string       `db:"full_name" json:"full_name"`
	Email     string       `db:"email" json:"email"`
	Password  string       `db:"password" json:"password"`
	CreatedAt time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt time.Time    `db:"updated_at" json:"updated_at"`
	DeletedAt sql.NullTime `db:"deleted_at" json:"deleted_at"`
}
