// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package sqlitestore

import (
	"context"
	"database/sql"
)

const bulkInsertGuests = `-- name: BulkInsertGuests :exec
INSERT INTO guests (
    full_name, email, document_number, occupation, profile_picture, event_id
) VALUES
    -- sqlc will dynamically replace these placeholders with actual data
    (?, ?, ?, ?, ?, ?)
`

type BulkInsertGuestsParams struct {
	FullName       string         `db:"full_name" json:"full_name"`
	Email          sql.NullString `db:"email" json:"email"`
	DocumentNumber string         `db:"document_number" json:"document_number"`
	Occupation     sql.NullString `db:"occupation" json:"occupation"`
	ProfilePicture sql.NullString `db:"profile_picture" json:"profile_picture"`
	EventID        string         `db:"event_id" json:"event_id"`
}

func (q *Queries) BulkInsertGuests(ctx context.Context, arg BulkInsertGuestsParams) error {
	_, err := q.db.ExecContext(ctx, bulkInsertGuests,
		arg.FullName,
		arg.Email,
		arg.DocumentNumber,
		arg.Occupation,
		arg.ProfilePicture,
		arg.EventID,
	)
	return err
}

const createCheckIn = `-- name: CreateCheckIn :one
INSERT INTO checkins (
    guest_id, event_id
) VALUES (
    ?, ?
) RETURNING id, event_id, guest_id, created_at
`

type CreateCheckInParams struct {
	GuestID string `db:"guest_id" json:"guest_id"`
	EventID string `db:"event_id" json:"event_id"`
}

// - CHECKIN ---
func (q *Queries) CreateCheckIn(ctx context.Context, arg CreateCheckInParams) (Checkin, error) {
	row := q.db.QueryRowContext(ctx, createCheckIn, arg.GuestID, arg.EventID)
	var i Checkin
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.GuestID,
		&i.CreatedAt,
	)
	return i, err
}

const createConfig = `-- name: CreateConfig :one
INSERT INTO config (
    id, template_image, printer, orientation, position_x, position_y, font_size, width_limiter
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, template_image, printer, orientation, updated_at, position_x, position_y, font_size, width_limiter
`

type CreateConfigParams struct {
	ID            string         `db:"id" json:"id"`
	TemplateImage sql.NullString `db:"template_image" json:"template_image"`
	Printer       sql.NullString `db:"printer" json:"printer"`
	Orientation   sql.NullString `db:"orientation" json:"orientation"`
	PositionX     sql.NullInt64  `db:"position_x" json:"position_x"`
	PositionY     sql.NullInt64  `db:"position_y" json:"position_y"`
	FontSize      sql.NullInt64  `db:"font_size" json:"font_size"`
	WidthLimiter  sql.NullInt64  `db:"width_limiter" json:"width_limiter"`
}

func (q *Queries) CreateConfig(ctx context.Context, arg CreateConfigParams) (Config, error) {
	row := q.db.QueryRowContext(ctx, createConfig,
		arg.ID,
		arg.TemplateImage,
		arg.Printer,
		arg.Orientation,
		arg.PositionX,
		arg.PositionY,
		arg.FontSize,
		arg.WidthLimiter,
	)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.TemplateImage,
		&i.Printer,
		&i.Orientation,
		&i.UpdatedAt,
		&i.PositionX,
		&i.PositionY,
		&i.FontSize,
		&i.WidthLimiter,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    name, primary_color, logo
) VALUES (
    ?, ?, ?
)
RETURNING id, name, primary_color, logo, created_at, updated_at, deleted_at
`

type CreateEventParams struct {
	Name         string `db:"name" json:"name"`
	PrimaryColor string `db:"primary_color" json:"primary_color"`
	Logo         string `db:"logo" json:"logo"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent, arg.Name, arg.PrimaryColor, arg.Logo)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrimaryColor,
		&i.Logo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createGuest = `-- name: CreateGuest :one
INSERT INTO guests (
    full_name, email, document_number, occupation, profile_picture, event_id
) VALUES (
    ?, ?, ?, ?, ?, ?
) RETURNING id, full_name, email, document_number, occupation, profile_picture, event_id, created_at, updated_at, deleted_at
`

type CreateGuestParams struct {
	FullName       string         `db:"full_name" json:"full_name"`
	Email          sql.NullString `db:"email" json:"email"`
	DocumentNumber string         `db:"document_number" json:"document_number"`
	Occupation     sql.NullString `db:"occupation" json:"occupation"`
	ProfilePicture sql.NullString `db:"profile_picture" json:"profile_picture"`
	EventID        string         `db:"event_id" json:"event_id"`
}

// - GUESTS ---
func (q *Queries) CreateGuest(ctx context.Context, arg CreateGuestParams) (Guest, error) {
	row := q.db.QueryRowContext(ctx, createGuest,
		arg.FullName,
		arg.Email,
		arg.DocumentNumber,
		arg.Occupation,
		arg.ProfilePicture,
		arg.EventID,
	)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.DocumentNumber,
		&i.Occupation,
		&i.ProfilePicture,
		&i.EventID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    full_name, email, password
) VALUES (
    ?, ?, ?
)
RETURNING id, full_name, email, password, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	FullName string `db:"full_name" json:"full_name"`
	Email    string `db:"email" json:"email"`
	Password string `db:"password" json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.FullName, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteConfig = `-- name: DeleteConfig :exec
DELETE FROM config
WHERE id = ?
`

func (q *Queries) DeleteConfig(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteConfig, id)
	return err
}

const getCheckIn = `-- name: GetCheckIn :one
SELECT 
    id, event_id, guest_id, created_at
FROM 
    checkins
WHERE 
    id = ?
LIMIT 
    1
`

func (q *Queries) GetCheckIn(ctx context.Context, id string) (Checkin, error) {
	row := q.db.QueryRowContext(ctx, getCheckIn, id)
	var i Checkin
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.GuestID,
		&i.CreatedAt,
	)
	return i, err
}

const getConfig = `-- name: GetConfig :one
SELECT 
    id, template_image, printer, orientation, updated_at, position_x, position_y, font_size, width_limiter 
FROM 
    config
WHERE 
    id = ?
LIMIT 
    1
`

// - CONFIG ---
func (q *Queries) GetConfig(ctx context.Context, id string) (Config, error) {
	row := q.db.QueryRowContext(ctx, getConfig, id)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.TemplateImage,
		&i.Printer,
		&i.Orientation,
		&i.UpdatedAt,
		&i.PositionX,
		&i.PositionY,
		&i.FontSize,
		&i.WidthLimiter,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT 
    id, name, primary_color, logo, created_at, updated_at, deleted_at 
FROM 
    events
WHERE 
    id = ? AND deleted_at IS NULL
LIMIT 
    1
`

// - EVENTS ---
func (q *Queries) GetEvent(ctx context.Context, id string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrimaryColor,
		&i.Logo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFirstConfig = `-- name: GetFirstConfig :one
SELECT 
    id, template_image, printer, orientation, updated_at, position_x, position_y, font_size, width_limiter 
FROM 
    config
LIMIT 
    1
`

func (q *Queries) GetFirstConfig(ctx context.Context) (Config, error) {
	row := q.db.QueryRowContext(ctx, getFirstConfig)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.TemplateImage,
		&i.Printer,
		&i.Orientation,
		&i.UpdatedAt,
		&i.PositionX,
		&i.PositionY,
		&i.FontSize,
		&i.WidthLimiter,
	)
	return i, err
}

const getGuest = `-- name: GetGuest :one
SELECT 
    id, full_name, email, document_number, occupation, profile_picture, event_id, created_at, updated_at, deleted_at
FROM 
    guests
WHERE 
    id = ? AND deleted_at IS NULL
LIMIT 
    1
`

func (q *Queries) GetGuest(ctx context.Context, id string) (Guest, error) {
	row := q.db.QueryRowContext(ctx, getGuest, id)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.DocumentNumber,
		&i.Occupation,
		&i.ProfilePicture,
		&i.EventID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGuestByDocumentNumber = `-- name: GetGuestByDocumentNumber :one
SELECT 
    id, full_name, email, document_number, occupation, profile_picture, event_id, created_at, updated_at, deleted_at
FROM 
    guests
WHERE 
    document_number = ? AND deleted_at IS NULL
LIMIT 
    1
`

func (q *Queries) GetGuestByDocumentNumber(ctx context.Context, documentNumber string) (Guest, error) {
	row := q.db.QueryRowContext(ctx, getGuestByDocumentNumber, documentNumber)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.DocumentNumber,
		&i.Occupation,
		&i.ProfilePicture,
		&i.EventID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT 
    id, full_name, email, password, created_at, updated_at, deleted_at 
FROM users
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

// - USERS ---
func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCheckIns = `-- name: ListCheckIns :many
SELECT 
    id, event_id, guest_id, created_at
FROM
    checkins
ORDER BY 
    created_at
`

func (q *Queries) ListCheckIns(ctx context.Context) ([]Checkin, error) {
	rows, err := q.db.QueryContext(ctx, listCheckIns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Checkin
	for rows.Next() {
		var i Checkin
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.GuestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigs = `-- name: ListConfigs :many
SELECT
    id, template_image, printer, orientation, updated_at, position_x, position_y, font_size, width_limiter
FROM 
    config
ORDER BY
    updated_at
`

func (q *Queries) ListConfigs(ctx context.Context) ([]Config, error) {
	rows, err := q.db.QueryContext(ctx, listConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(
			&i.ID,
			&i.TemplateImage,
			&i.Printer,
			&i.Orientation,
			&i.UpdatedAt,
			&i.PositionX,
			&i.PositionY,
			&i.FontSize,
			&i.WidthLimiter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT
    id, name, primary_color, logo, created_at, updated_at, deleted_at
FROM 
    events
WHERE deleted_at IS NULL
ORDER BY
    name
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PrimaryColor,
			&i.Logo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuests = `-- name: ListGuests :many
SELECT 
    id, full_name, email, document_number, occupation, profile_picture, event_id, created_at, updated_at, deleted_at
FROM
    guests
WHERE
    deleted_at IS NULL
ORDER BY 
    full_name
`

func (q *Queries) ListGuests(ctx context.Context) ([]Guest, error) {
	rows, err := q.db.QueryContext(ctx, listGuests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guest
	for rows.Next() {
		var i Guest
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.DocumentNumber,
			&i.Occupation,
			&i.ProfilePicture,
			&i.EventID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT
    id, full_name, email, password, created_at, updated_at, deleted_at
FROM 
    users
WHERE deleted_at IS NULL
ORDER BY
    full_name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEvent = `-- name: SoftDeleteEvent :exec
UPDATE events
SET deleted_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteEvent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteEvent, id)
	return err
}

const softDeleteGuest = `-- name: SoftDeleteGuest :exec
UPDATE
    guests
SET
    deleted_at = NOW()
WHERE 
    id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteGuest(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteGuest, id)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, id)
	return err
}

const updateConfig = `-- name: UpdateConfig :one
UPDATE config
SET 
    template_image = ?1,
    printer = ?2,
    orientation = ?3,
    position_x = ?4,
    position_y = ?5,
    font_size = ?6,
    width_limiter = ?7,
    updated_at = CURRENT_TIMESTAMP
WHERE 
    id = ?8
RETURNING id, template_image, printer, orientation, updated_at, position_x, position_y, font_size, width_limiter
`

type UpdateConfigParams struct {
	TemplateImage sql.NullString `db:"template_image" json:"template_image"`
	Printer       sql.NullString `db:"printer" json:"printer"`
	Orientation   sql.NullString `db:"orientation" json:"orientation"`
	PositionX     sql.NullInt64  `db:"position_x" json:"position_x"`
	PositionY     sql.NullInt64  `db:"position_y" json:"position_y"`
	FontSize      sql.NullInt64  `db:"font_size" json:"font_size"`
	WidthLimiter  sql.NullInt64  `db:"width_limiter" json:"width_limiter"`
	ID            string         `db:"id" json:"id"`
}

func (q *Queries) UpdateConfig(ctx context.Context, arg UpdateConfigParams) (Config, error) {
	row := q.db.QueryRowContext(ctx, updateConfig,
		arg.TemplateImage,
		arg.Printer,
		arg.Orientation,
		arg.PositionX,
		arg.PositionY,
		arg.FontSize,
		arg.WidthLimiter,
		arg.ID,
	)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.TemplateImage,
		&i.Printer,
		&i.Orientation,
		&i.UpdatedAt,
		&i.PositionX,
		&i.PositionY,
		&i.FontSize,
		&i.WidthLimiter,
	)
	return i, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET 
    name = ?1,
    primary_color = ?2,
    logo = ?3,
    updated_at = CURRENT_TIMESTAMP
WHERE 
    id = ?4
RETURNING id, name, primary_color, logo, created_at, updated_at, deleted_at
`

type UpdateEventParams struct {
	Name         string `db:"name" json:"name"`
	PrimaryColor string `db:"primary_color" json:"primary_color"`
	Logo         string `db:"logo" json:"logo"`
	ID           string `db:"id" json:"id"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.Name,
		arg.PrimaryColor,
		arg.Logo,
		arg.ID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrimaryColor,
		&i.Logo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateGuest = `-- name: UpdateGuest :one
UPDATE 
    guests
SET 
    full_name = ?1,
    email = ?2,
    occupation = ?3,
    profile_picture = ?4,
    document_number = ?5,
    event_id = ?6,
    updated_at = CURRENT_TIMESTAMP
WHERE 
    id = ?7
RETURNING id, full_name, email, document_number, occupation, profile_picture, event_id, created_at, updated_at, deleted_at
`

type UpdateGuestParams struct {
	FullName       string         `db:"full_name" json:"full_name"`
	Email          sql.NullString `db:"email" json:"email"`
	Occupation     sql.NullString `db:"occupation" json:"occupation"`
	ProfilePicture sql.NullString `db:"profile_picture" json:"profile_picture"`
	DocumentNumber string         `db:"document_number" json:"document_number"`
	EventID        string         `db:"event_id" json:"event_id"`
	ID             string         `db:"id" json:"id"`
}

func (q *Queries) UpdateGuest(ctx context.Context, arg UpdateGuestParams) (Guest, error) {
	row := q.db.QueryRowContext(ctx, updateGuest,
		arg.FullName,
		arg.Email,
		arg.Occupation,
		arg.ProfilePicture,
		arg.DocumentNumber,
		arg.EventID,
		arg.ID,
	)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.DocumentNumber,
		&i.Occupation,
		&i.ProfilePicture,
		&i.EventID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
    full_name = ?1,
    email = ?2,
    password = ?3,
    updated_at = CURRENT_TIMESTAMP
WHERE 
    id = ?4
RETURNING id, full_name, email, password, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	FullName string `db:"full_name" json:"full_name"`
	Email    string `db:"email" json:"email"`
	Password string `db:"password" json:"password"`
	ID       string `db:"id" json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.FullName,
		arg.Email,
		arg.Password,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
