basePath: /
definitions:
  sqlitestore.CreateUserParams:
    properties:
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
    type: object
  sqlitestore.User:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: string
      password:
        type: string
      updated_at:
        type: string
    type: object
  utils.ErrorResponse:
    properties:
      message:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://localhost:8080/swagger/index.html
host: localhost:8080
info:
  contact:
    email: avgsolheiro@gmail.com
    name: Armando Solheiro
  description: API used on Kiosk Services.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: KioskAPI
  version: "1.0"
paths:
  /users:
    get:
      description: List all active users in database.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/sqlitestore.User'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: List all active users.
      tags:
      - user
    post:
      consumes:
      - application/json
      description: Create an active user in database with given parameters.
      parameters:
      - description: Add account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/sqlitestore.CreateUserParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/sqlitestore.User'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Create an user
      tags:
      - user
swagger: "2.0"
